<a href="https://colab.research.google.com/github/ganeshrebbas/python-basic/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('Salaries.csv')

In [6]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [7]:
df.head

<bound method NDFrame.head of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [8]:
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [9]:
df.tail

<bound method NDFrame.tail of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [10]:
df.shape

(78, 6)

In [11]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [12]:
df.isnull

<bound method DataFrame.isnull of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [13]:
pd.set_option('display.max_rows',None)

In [14]:
df.isnull

<bound method DataFrame.isnull of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646>

In [20]:
df.notnull()

    rank  discipline   phd  service   sex  salary
0   True        True  True     True  True    True
1   True        True  True     True  True    True
2   True        True  True     True  True    True
3   True        True  True     True  True    True
4   True        True  True     True  True    True
5   True        True  True     True  True    True
6   True        True  True     True  True    True
7   True        True  True     True  True    True
8   True        True  True     True  True    True
9   True        True  True     True  True    True
10  True        True  True     True  True    True
11  True        True  True     True  True    True
12  True        True  True     True  True    True
13  True        True  True     True  True    True
14  True        True  True     True  True    True
15  True        True  True     True  True    True
16  True        True  True     True  True    True
17  True        True  True     True  True    True
18  True        True  True     True  True    True
19  True        True  True     True  True    True
20  True        True  True     True  True    True
21  True        True  True     True  True    True
22  True        True  True     True  True    True
23  True        True  True     True  True    True
24  True        True  True     True  True    True
25  True        True  True     True  True    True
26  True        True  True     True  True    True
27  True        True  True     True  True    True
28  True        True  True     True  True    True
29  True        True  True     True  True    True
30  True        True  True     True  True    True
31  True        True  True     True  True    True
32  True        True  True     True  True    True
33  True        True  True     True  True    True
34  True        True  True     True  True    True
35  True        True  True     True  True    True
36  True        True  True     True  True    True
37  True        True  True     True  True    True
38  True        True  True     True  True    True
39  True        True  True     True  True    True
40  True        True  True     True  True    True
41  True        True  True     True  True    True
42  True        True  True     True  True    True
43  True        True  True     True  True    True
44  True        True  True     True  True    True
45  True        True  True     True  True    True
46  True        True  True     True  True    True
47  True        True  True     True  True    True
48  True        True  True     True  True    True
49  True        True  True     True  True    True
50  True        True  True     True  True    True
51  True        True  True     True  True    True
52  True        True  True     True  True    True
53  True        True  True     True  True    True
54  True        True  True     True  True    True
55  True        True  True     True  True    True
56  True        True  True     True  True    True
57  True        True  True     True  True    True
58  True        True  True     True  True    True
59  True        True  True     True  True    True
60  True        True  True     True  True    True
61  True        True  True     True  True    True
62  True        True  True     True  True    True
63  True        True  True     True  True    True
64  True        True  True     True  True    True
65  True        True  True     True  True    True
66  True        True  True     True  True    True
67  True        True  True     True  True    True
68  True        True  True     True  True    True
69  True        True  True     True  True    True
70  True        True  True     True  True    True
71  True        True  True     True  True    True
72  True        True  True     True  True    True
73  True        True  True     True  True    True
74  True        True  True     True  True    True
75  True        True  True     True  True    True
76  True        True  True     True  True    True
77  True        True  True     True  True    True